### ISSUE TITLE
[Java] Implement inRange

### ISSUE THREAD

**Issue by SergeyOvchinnik** [SergeyOvchinnik/class6#10]
There is an unimplemented method called inRange in the Utilities class.

Please implement this method:
https://github.com/SergeyOvchinnik/class6/blob/8f1773c100e2145e09ee75f91e3dedc41e658e67/src/Utilities.java#L11

**Comment by plzbekind** [comment]
I will do this one

**Comment by SergeyOvchinnik** [comment]
Resolved in https://github.com/SergeyOvchinnik/class6/pull/30
