### ISSUE TITLE
[Java] Implement threeXPlusOne

### ISSUE THREAD

**Issue by SergeyOvchinnik** [SergeyOvchinnik/class6#14]
There is an unimplemented method called threeXPlusOne in the Utilities class.

Please implement this method:
https://github.com/SergeyOvchinnik/class6/blob/8f1773c100e2145e09ee75f91e3dedc41e658e67/src/Utilities.java#L35

**Comment by lordsheps** [comment]
I'll work on it

**Comment by SergeyOvchinnik** [comment]
Resolved in https://github.com/SergeyOvchinnik/class6/pull/25
