### ISSUE TITLE
[Java] Implement ordered

### ISSUE THREAD

**Issue by SergeyOvchinnik** [SergeyOvchinnik/class6#17]
There is an unimplemented method called ordered in the Utilities class.

Please implement this method:
https://github.com/SergeyOvchinnik/class6/blob/8f1773c100e2145e09ee75f91e3dedc41e658e67/src/Utilities.java#L54

**Comment by tasbehanawaz** [comment]
I'll fix this.

**Comment by SergeyOvchinnik** [comment]
Resolved in https://github.com/SergeyOvchinnik/class6/pull/32
