### ISSUE TITLE
[Java] arrayMaxMin method does not check valid input

### ISSUE THREAD

**Issue by SergeyOvchinnik** [SergeyOvchinnik/class6#22]
Method arrayMaxMin in the Util2 class does not currently check whether the input array is valid. Please implement checks for the input array value so that the method works correctly for null values and empty arrays. Choose some output that would make sense in those situations.

https://github.com/SergeyOvchinnik/class6/blob/0400ab58c664eb22c2a25e537e688d586ac239f0/src/Util2.java#L50

**Comment by XinyuZ0416** [comment]
I'll work on this

**Comment by SergeyOvchinnik** [comment]
Resolved in https://github.com/SergeyOvchinnik/class6/pull/23
