### ISSUE TITLE
[Java] What the hell is b?

### ISSUE THREAD

**Issue by SergeyOvchinnik** [SergeyOvchinnik/class6#4]
There is a method in the PoorCode class named "b". What does that even mean? Rename the method and add some comments describing what it does!

https://github.com/SergeyOvchinnik/class6/blob/8f1773c100e2145e09ee75f91e3dedc41e658e67/src/PoorCode.java#L166

**Comment by mikulobams** [comment]
ok. On it

**Comment by SergeyOvchinnik** [comment]
Resolved in https://github.com/SergeyOvchinnik/class6/pull/29
