### ISSUE TITLE
[JavaScript] Implement ordered

### ISSUE THREAD

**Issue by SergeyOvchinnik** [SergeyOvchinnik/class6#57]
There is an unimplemented function called ordered in the Utilities class.

Please implement this function:
https://github.com/SergeyOvchinnik/class6/blob/c31a202754ca4c0a89d9755cae61f20104edf159/web/Utilities.js#L51

**Comment by CJO16** [comment]
I'll work on this.

**Comment by SergeyOvchinnik** [comment]
Resolved in https://github.com/SergeyOvchinnik/class6/pull/60
