### ISSUE TITLE
[Java] Code quality in locateTopEven

### ISSUE THREAD

**Issue by SergeyOvchinnik** [SergeyOvchinnik/class6#8]
There is a method called locateTopEven in the PoorCode class that makes me want to locateWhoeverWroteThisMethod.

Please fix code quality issues in this method:
https://github.com/SergeyOvchinnik/class6/blob/8f1773c100e2145e09ee75f91e3dedc41e658e67/src/PoorCode.java#L58

**Comment by Jdiva1234** [comment]
i will fix this.

**Comment by SergeyOvchinnik** [comment]
Resolved in https://github.com/SergeyOvchinnik/class6/pull/31
