### ISSUE TITLE
[Java] Implement countOccurences

### ISSUE THREAD

**Issue by SergeyOvchinnik** [SergeyOvchinnik/class6#9]
There is an unimplemented method called countOccurences in the Utilities class.

Please implement this method:
https://github.com/SergeyOvchinnik/class6/blob/8f1773c100e2145e09ee75f91e3dedc41e658e67/src/Utilities.java#L5

**Comment by Iemberk** [comment]
I will work on this.

**Comment by SergeyOvchinnik** [comment]
Resolved in https://github.com/SergeyOvchinnik/class6/pull/27
